name: mlops-example-tensorflow-regression
#accion para pusear cambios 
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python model.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python model.py
          #como dejar un readme
          echo "##Model Metrics" > report.md
          cat metrics.txt >> report.md

          echo "##\n## Model Performance"
          echo "model Performace Metrics On the Plot Below"

          cml-publish model_results.png --md report.md

          cml-send-comment report.md